{% set name = "opentelemetry-instrumentation-langchain" %}
{% set version = "0.47.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_langchain-{{ version }}.tar.gz
  sha256: ffdffde8e7dce9cfd2909ed652cef15226c7b8e27726d41079a079a41f4167e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5
  run_constrained:
    - langchain >=0.3.15,<0.4.0

test:
  imports:
    - opentelemetry.instrumentation.langchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - langchain

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Langchain instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
